"""
src/embeddings.py
─────────────────────────────────────────────────────────────────
Sage AI — Embedding Pipeline
 
What this file does:
1. Loads shlokas from data/gita_shlokas.json
2. Converts each shloka's `embed_text` into a vector using
   sentence-transformers (all-MiniLM-L6-v2 — free, local, 384-dim)
3. Stores vectors + metadata in a persistent ChromaDB collection
   so they only need to be computed once.
 
Run:
    python src/embeddings.py
 
After this runs, data/chroma_db/ will contain your vector store.
This folder is .gitignored — it's regenerated by anyone who clones
the repo and runs this script.
"""
 
import os
from pathlib import Path
 
import chromadb
from chromadb.utils import embedding_functions
from dotenv import load_dotenv
 
from ingest import load_shlokas
 
load_dotenv()
 
# ── Config ────────────────────────────────────────────────────────
DATA_DIR = Path(__file__).parent.parent / "data"
CHROMA_PERSIST_DIR = str(DATA_DIR / "chroma_db")
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", "all-MiniLM-L6-v2")
COLLECTION_NAME = "gita_shlokas"
 
 
def get_chroma_client() -> chromadb.PersistentClient:
    """Returns a persistent ChromaDB client — data survives restarts."""
    return chromadb.PersistentClient(path=CHROMA_PERSIST_DIR)
 
 
def get_embedding_function():
    """
    Uses sentence-transformers locally — no API key, no cost.
    all-MiniLM-L6-v2 is small (80MB), fast, and great for semantic search.
    """
    return embedding_functions.SentenceTransformerEmbeddingFunction(
        model_name=EMBEDDING_MODEL
    )
 
 
def build_collection(shlokas: list[dict]) -> chromadb.Collection:
    """
    Creates (or resets) the gita_shlokas collection and adds all
    shlokas as embedded documents with metadata for filtering.
    """
    client = get_chroma_client()
    embedding_fn = get_embedding_function()
 
    # Drop existing collection so re-runs don't duplicate data
    try:
        client.delete_collection(COLLECTION_NAME)
        print(f"  Cleared existing '{COLLECTION_NAME}' collection")
    except Exception:
        pass
 
    collection = client.create_collection(
        name=COLLECTION_NAME,
        embedding_function=embedding_fn,
        metadata={"description": "Bhagavad Gita shlokas with emotion/topic tags"},
    )
 
    ids = [s["id"] for s in shlokas]
    documents = [s["embed_text"] for s in shlokas]
    metadatas = [
        {
            "chapter": s["chapter"],
            "chapter_title": s["chapter_title"],
            "verse": s["verse"],
            "sanskrit": s["sanskrit"],
            "translation": s["translation"],
            "emotions": ", ".join(s["emotions"]),  # Chroma metadata must be flat
        }
        for s in shlokas
    ]
 
    collection.add(ids=ids, documents=documents, metadatas=metadatas)
    return collection
 
 
def test_retrieval(collection: chromadb.Collection, query: str, n: int = 3) -> None:
    """Quick sanity check — runs a sample query and prints results."""
    results = collection.query(query_texts=[query], n_results=n)
 
    print(f"\n  Query: \"{query}\"")
    print(f"  Top {n} results:")
    for i, (doc_id, meta, distance) in enumerate(
        zip(results["ids"][0], results["metadatas"][0], results["distances"][0]), 1
    ):
        print(f"    {i}. [{doc_id}] Ch.{meta['chapter']} V.{meta['verse']} "
              f"— similarity: {1 - distance:.3f}")
        print(f"       \"{meta['translation'][:90]}...\"")
 
 
if __name__ == "__main__":
    print("🌿 Sage AI — Building embeddings...\n")
 
    print("Loading shlokas...")
    shlokas = load_shlokas()
    print(f"  Loaded {len(shlokas)} shlokas")
 
    print(f"\nEmbedding with model: {EMBEDDING_MODEL}")
    print("  (First run downloads the model — ~80MB, one-time)")
    collection = build_collection(shlokas)
    print(f"  ✅ Stored {collection.count()} embedded shlokas in ChromaDB")
    print(f"  📁 Persisted to: {CHROMA_PERSIST_DIR}")
 
    print("\n─── Sanity Check — Sample Retrievals ───────────────────")
    test_retrieval(collection, "I feel anxious about my future and don't know what to do")
    test_retrieval(collection, "My friend passed away and I can't stop grieving")
    test_retrieval(collection, "I feel weak and like a coward, I want to give up")
    print("\n──────────────────────────────────────────────────────────")
 
    print("\n Day 2 embedding pipeline complete")